version: "3"

volumes: # 自定义数据卷，位于宿主机/var/lib/docker/volumes内
 myproject_db_vol: # 定义数据卷同步容器内mysql数据
 myproject_redis_vol: # 定义数据卷同步redis容器内数据
 myproject_media_vol: # 定义数据卷同步media文件夹数据
 certs:
 vhost:
 html:
 dhparam:

services:
 web:
   build: ./mmm957 # 使用myproject目录下的Dockerfile
   expose:
      - "8000"
   volumes:
      - ./VincentBot:/var/www/html/VincentBot # 挂载项目代码
      - ./compose/uwsgi:/tmp # 挂载uwsgi日志
   environment:
      - DEBUG=False
   restart: always
   tty: true
   stdin_open: true

 nginx-proxy:
   image: jwilder/nginx-proxy:alpine
   restart: always
   container_name: nginx-proxy
   ports:
      - "80:80"
      - "443:443"
   volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - vhost:/etc/nginx/vhost.d
      - certs:/etc/nginx/certs:ro

 nginx-proxy-letsencrypt:
   image: jrcs/letsencrypt-nginx-proxy-companion
   restart: always
   depends_on:
      - "nginx-proxy"
   volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
   environment:
#     - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=v39215068@gmail.com

 nginx:
   build: ./compose/nginx
   volumes:
      - ./VincentBot/static:/usr/share/nginx/html/static # 挂载静态文件
      - ./compose/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      - ./compose/nginx/log:/var/log/nginx # 挂载日志
      - myproject_media_vol:/usr/share/nginx/html/media # 挂载用户上传媒体文件
   links:
      - web
   depends_on:
      - web
   restart: always
   environment:
      - VIRTUAL_HOST=dancing2music.ml,www.dancing2music.ml
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=dancing2music.ml,www.dancing2music.ml
      - LETSENCRYPT_EMAIL=v39215068@gmail.com